import { fmt } from "@/lib/currency";

export const CUSTOMERS = [
  {
    id: "CUS-001",
    name: "Eleanor Henderson",
    email: "eleanor.h@gmail.com",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDGc4FzpFxsv5V1S8kN71MpChqtmors2umTeZJYaCHHFVfHuk173OVxdBWhMoiIEIenapKIUiQmfkG5miT8PCWg5a5cQaLP37kZD-c_7SvqhIXDKYE4aGvC1FA2spz6eGEwKBdiTdVetbLYgMddwSldgc9eDdz8DgQ1a-LpMWZAKUmHBnfAXmJv8cSk3TZYEMw9wPu-Kf-QCXUaNKhu7kOigzyvN85ZKjdMCPRPPSRYfhBlXhNGEVKvtvRIX-iCkF5m3WoDK6RCx8sk",
    joinedAgo: "2 months ago",
    orders: 12,
    ltvRaw: 14250,
    ltv: fmt(14250),
    status: "active",
    pets: ["Golden Retriever"],
  },
  {
    id: "CUS-002",
    name: "James Miller",
    email: "j.miller88@outlook.com",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAjVNRucEBNDxhE0J5QBMyyZdsE_NXVJY9frgA1Z4atiLU8fCCV03_LL_lAY8e_vU0jqi84x7V_vn3iP2_5EStDvZj9w933c7p7aTAy62-lv328RwRx5eMSHOhxUpZGYlWjAMAGDAIFJ7Ff0akL-IiVCaUNsob0A-RPIrkIjarSQxSPibYEysDYqU-sw3FDenOZ-1JyEew_3l3F_wOb-b19md0ebHAbc4XwQv8J72sGc-m-3EtUVvuZdihY2u7ZsCICxYGa5v49oRtq",
    joinedAgo: "6 months ago",
    orders: 24,
    ltvRaw: 38420,
    ltv: fmt(38420),
    status: "vip",
    pets: ["Labrador", "Persian Cat"],
  },
  {
    id: "CUS-003",
    name: "Sarah Chen",
    email: "sarah.chen@techcorp.com",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCM0glzAox1V_r4-sC2RQunZvMfcz1pPG3nPbWtBI1tX9QRlcFx-B73dDEFThIuZyGPYG9JhfrqwEz9sk6We50nZJpADz7qNr_Oz7ez9_PeE3NBG5Tg3zzlgfpd9KQtepD-16LLeweJJReWYRINJy3B1bXkESH-FrZsFuHRfkT4w-HUN8tovHqjle-1DyJE25Hn4Qr7lvxCoUhjNhzkyatRVKAepmsAyyzkvGHqneZINoY7F3vJbi4PXqKD7A_JegG6279wdDuiGSKT",
    joinedAgo: "1 year ago",
    orders: 8,
    ltvRaw: 8900,
    ltv: fmt(8900),
    status: "inactive",
    pets: ["Siamese Cat"],
  },
  {
    id: "CUS-004",
    name: "Michael Thompson",
    email: "m.thompson@icloud.com",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDf94YaqzEpIvIasFIrs3dOD0e2j9AIQz6LZWp6Y6Hr_U0UrS_Pvo2nfEK1LN2N7DwXkciSO8xM_2fAoxEsdNM1RLamPyV8C6R3PcDYxZwgplbFF3hoqm07p4as0DT31bxrmcuasx90hf0tI-gbs_td2bN-DFOBGXdFa3DAgz4nCoMz6mzjEmiQY80KT9yKgf_7FcthLZYVQg0ge9dgfTBlMLahVfxsX5MxsaCsFI-YnE537l9VeVHR4EoZx55B8ycQ-UnAt_agoxfR",
    joinedAgo: "3 months ago",
    orders: 15,
    ltvRaw: 21150,
    ltv: fmt(21150),
    status: "active",
    pets: ["Beagle"],
  },
  {
    id: "CUS-005",
    name: "Linda White",
    email: "linda.w@verizon.net",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCCaIjUACJiv6wTQPQFriBB-9Ec6y5N21pyyuDyAGY8mg7KwnST9z89U00Ct3KhgJvLQHE3EjbQk83p8wXe5JX51Wm04D4WhS-_iTd2J_YnZn2hhApwZLWIqaA-KH7U7Bpos2ce5ZFzGQ1AwQNdc20WbqiYvKKjvQAzoXx6crOrzxJFtZqAHWeZgeFoTvfF3CYOrnH8aUg6w6Ex60IHDlZlc11UOtZY4cEjxizD4aBhH4SY1aSLnU2D7OjkgvvzutXuZvYibNC9oX6r",
    joinedAgo: "2 years ago",
    orders: 42,
    ltvRaw: 52400,
    ltv: fmt(52400),
    status: "vip",
    pets: ["Poodle", "Tabby Cat", "Budgie"],
  },
  {
    id: "CUS-006",
    name: "Raj Sharma",
    email: "raj.sharma@gmail.com",
    avatar: null,
    joinedAgo: "4 months ago",
    orders: 6,
    ltvRaw: 7200,
    ltv: fmt(7200),
    status: "active",
    pets: ["German Shepherd"],
  },
  {
    id: "CUS-007",
    name: "Priya Patel",
    email: "priya.patel@hotmail.com",
    avatar: null,
    joinedAgo: "1 year ago",
    orders: 35,
    ltvRaw: 48600,
    ltv: fmt(48600),
    status: "vip",
    pets: ["Shih Tzu", "Ragdoll Cat"],
  },
  {
    id: "CUS-008",
    name: "David Wilson",
    email: "d.wilson@yahoo.com",
    avatar: null,
    joinedAgo: "8 months ago",
    orders: 3,
    ltvRaw: 3100,
    ltv: fmt(3100),
    status: "inactive",
    pets: ["Hamster"],
  },
  {
    id: "CUS-009",
    name: "Anita Gupta",
    email: "anita.gupta@outlook.com",
    avatar: null,
    joinedAgo: "5 months ago",
    orders: 9,
    ltvRaw: 11800,
    ltv: fmt(11800),
    status: "active",
    pets: ["Labrador"],
  },
  {
    id: "CUS-010",
    name: "Tom Anderson",
    email: "t.anderson@icloud.com",
    avatar: null,
    joinedAgo: "7 months ago",
    orders: 19,
    ltvRaw: 26400,
    ltv: fmt(26400),
    status: "active",
    pets: ["Golden Retriever", "Parrot"],
  },
  {
    id: "CUS-011",
    name: "Nina Rodriguez",
    email: "nina.r@gmail.com",
    avatar: null,
    joinedAgo: "1.5 years ago",
    orders: 28,
    ltvRaw: 39900,
    ltv: fmt(39900),
    status: "vip",
    pets: ["Pomeranian"],
  },
  {
    id: "CUS-012",
    name: "Chris Evans",
    email: "chris.e@protonmail.com",
    avatar: null,
    joinedAgo: "10 months ago",
    orders: 5,
    ltvRaw: 5750,
    ltv: fmt(5750),
    status: "inactive",
    pets: ["Turtle"],
  },
];

export const STATUS_STYLES = {
  active: {
    bg:   "bg-green-100",
    text: "text-green-800",
    border: "border-green-200",
    label: "Active",
  },
  vip: {
    bg:   "bg-primary-fixed/30",
    text: "text-primary",
    border: "border-primary-fixed-dim",
    label: "VIP Member",
  },
  inactive: {
    bg:   "bg-surface-container-high",
    text: "text-on-surface-variant",
    border: "border-outline-variant",
    label: "Inactive",
  },
};
